// preload.js — runs in the control panel pane before controls.html loads. Exposes a
// small, explicit API bridge instead of giving the renderer raw Node/IPC access.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  sendCompose: (text, targets) => ipcRenderer.invoke("send:compose", { text, targets }),
  sendForward: (source, targets) => ipcRenderer.invoke("send:forward", { source, targets }),
  regenerate: (site) => ipcRenderer.invoke("send:regenerate", site),
  setRouting: (source, target, enabled) => ipcRenderer.invoke("routing:set", { source, target, enabled }),
  pauseAllRouting: () => ipcRenderer.invoke("routing:pause-all"),
  stopAllRouting: () => ipcRenderer.invoke("routing:stop-all"),
  autoAllRouting: () => ipcRenderer.invoke("routing:auto-all"),
  setParticipant: (site, enabled) => ipcRenderer.invoke("participants:set", { site, enabled }),
  startHouseRule: (mode, topic, rounds) => ipcRenderer.invoke("houserule:start", { mode, topic, rounds }),
  stopHouseRule: () => ipcRenderer.invoke("houserule:stop"),
  pauseHouseRule: () => ipcRenderer.invoke("houserule:pause"),
  resumeHouseRule: () => ipcRenderer.invoke("houserule:resume"),
  wrapUpBrainstorm: () => ipcRenderer.invoke("houserule:wrap-up-brainstorm"),
  setRole: (site, role) => ipcRenderer.invoke("roles:set", { site, role }),
  savePrompt: (id, name, text) => ipcRenderer.invoke("prompts:save", { id, name, text }),
  deletePrompt: (id) => ipcRenderer.invoke("prompts:delete", id),
  sendPrompt: (text) => ipcRenderer.invoke("prompts:send", { text }),
  openPromptEditor: (id) => ipcRenderer.invoke("prompts:open-editor", id),
  closePromptEditor: () => ipcRenderer.invoke("prompt-editor:close"),
  onPromptsChanged: (cb) => ipcRenderer.on("prompts-changed", (_e, payload) => cb(payload)),
  getState: () => ipcRenderer.invoke("state:get"),
  clearTranscript: () => ipcRenderer.invoke("transcript:clear"),
  togglePin: (id) => ipcRenderer.invoke("transcript:toggle-pin", id),
  reloadSite: (site) => ipcRenderer.invoke("site:reload", site),
  startNewChatAll: () => ipcRenderer.invoke("sites:new-chat-all"),
  inspectSite: (site) => ipcRenderer.invoke("site:inspect", site),
  listSites: () => ipcRenderer.invoke("site:list"),
  chooseDocument: () => ipcRenderer.invoke("document:choose"),
  readDocument: (path) => ipcRenderer.invoke("document:read", path),
  sendDocument: (path, targets) => ipcRenderer.invoke("document:send", { path, targets }),
  closeDocumentViewer: () => ipcRenderer.invoke("document-viewer:close"),
  setZoom: (site, factor) => ipcRenderer.invoke("site:zoom", { site, factor }),
  pickSelector: (site, role) => ipcRenderer.invoke("selector:pick", { site, role }),
  clearSelectorOverride: (site, role) => ipcRenderer.invoke("selector:clear", { site, role }),
  runSelfTest: (site) => ipcRenderer.invoke("selftest:run", { site }),
  runTuner: () => ipcRenderer.invoke("tuner:run"),
  onTunerState: (cb) => ipcRenderer.on("tuner-state", (_e, payload) => cb(payload)),
  listSavedLogins: () => ipcRenderer.invoke("logins:list"),
  saveLogin: (site, label, username, password) => ipcRenderer.invoke("logins:save", { site, label, username, password }),
  deleteLogin: (site, id) => ipcRenderer.invoke("logins:delete", { site, id }),
  fillLogin: (site, id) => ipcRenderer.invoke("logins:fill", { site, id }),
  openSequenceEditor: () => ipcRenderer.invoke("sequence:open"),
  closeSequenceEditor: () => ipcRenderer.invoke("sequence-editor:close"),
  runSequence: (steps) => ipcRenderer.invoke("sequence:run", { steps }),
  stopSequence: () => ipcRenderer.invoke("sequence:stop"),
  onSequenceState: (cb) => ipcRenderer.on("sequence-state", (_e, payload) => cb(payload)),
  toggleWindowCollapse: (which) => ipcRenderer.invoke("window:toggle-collapse", { which }),
  openFeed: () => ipcRenderer.invoke("feed:open"),
  closeFeed: () => ipcRenderer.invoke("feed-window:close"),
  feedHistory: () => ipcRenderer.invoke("feed:history"),
  onCapture: (cb) => ipcRenderer.on("capture", (_e, payload) => cb(payload)),
  onWindowCollapseChanged: (cb) => ipcRenderer.on("window-collapse-changed", (_e, payload) => cb(payload)),
  onSent: (cb) => ipcRenderer.on("sent", (_e, payload) => cb(payload)),
  onSendError: (cb) => ipcRenderer.on("send-error", (_e, payload) => cb(payload)),
  onWaitingChanged: (cb) => ipcRenderer.on("waiting-changed", (_e, payload) => cb(payload)),
  onHouseRuleState: (cb) => ipcRenderer.on("houserule-state", (_e, payload) => cb(payload)),
  onLog: (cb) => ipcRenderer.on("log", (_e, payload) => cb(payload)),
  onLedgerEntry: (cb) => ipcRenderer.on("ledger-entry", (_e, payload) => cb(payload)),
  startManagedTask: (userRequest) => ipcRenderer.invoke("manager:start-task", { userRequest }),
  pauseManagedTask: () => ipcRenderer.invoke("manager:pause"),
  resumeManagedTask: () => ipcRenderer.invoke("manager:resume"),
  stopManagedTask: () => ipcRenderer.invoke("manager:stop"),
  approveManagerAction: () => ipcRenderer.invoke("manager:approve"),
  rejectManagerAction: (reason) => ipcRenderer.invoke("manager:reject", { reason }),
  configureManagerProvider: (config) => ipcRenderer.invoke("manager:configure-provider", config),
  testManagerConnection: () => ipcRenderer.invoke("manager:test-connection"),
  getManagerState: () => ipcRenderer.invoke("manager:get-state"),
  onManagerState: (cb) => ipcRenderer.on("manager-state", (_e, payload) => cb(payload)),
  onManagerLog: (cb) => ipcRenderer.on("manager-log", (_e, payload) => cb(payload)),
  atelierDetect: () => ipcRenderer.invoke("atelier:detect"),
  atelierStages: () => ipcRenderer.invoke("atelier:stages"),
  atelierGetSettings: () => ipcRenderer.invoke("atelier:get-settings"),
  atelierSetSettings: (patch) => ipcRenderer.invoke("atelier:set-settings", patch),
  atelierCheck: (role, path) => ipcRenderer.invoke("atelier:check", { role, path }),
  atelierStatus: (dir) => ipcRenderer.invoke("atelier:status", dir),
  atelierDeliver: (turn, jobId) => ipcRenderer.invoke("atelier:deliver", { turn, jobId }),
  dbStatus: () => ipcRenderer.invoke("db:status"),
  dbRecentMessages: (limit) => ipcRenderer.invoke("db:recent-messages", limit),
  dbMemorySummary: () => ipcRenderer.invoke("db:memory-summary"),
  dbMemoryCreate: (type, data) => ipcRenderer.invoke("db:memory-create", { type, data }),
  dbMemorySearch: (query) => ipcRenderer.invoke("db:memory-search", query),
  dbProjectState: () => ipcRenderer.invoke("db:project-state"),
  sdGetSettings: () => ipcRenderer.invoke("sd:get-settings"),
  sdSetSettings: (patch) => ipcRenderer.invoke("sd:set-settings", patch),
  sdTest: () => ipcRenderer.invoke("sd:test"),
  sdModels: () => ipcRenderer.invoke("sd:models"),
  sdGenerate: (opts) => ipcRenderer.invoke("sd:generate", opts),
  sdGallery: (limit) => ipcRenderer.invoke("sd:gallery", limit),
  onSdImage: (cb) => ipcRenderer.on("sd-image", (_e, payload) => cb(payload)),
  systemInfo: () => ipcRenderer.invoke("system:info"),
  systemReport: () => ipcRenderer.invoke("system:report"),
  onFocusPanel: (cb) => ipcRenderer.on("focus-panel", (_e, payload) => cb(payload)),
  lsiGetSettings: () => ipcRenderer.invoke("lsi:get-settings"),
  lsiSetSettings: (patch) => ipcRenderer.invoke("lsi:set-settings", patch),
  lsiTest: () => ipcRenderer.invoke("lsi:test"),
  ollamaDetect: () => ipcRenderer.invoke("ollama:detect"),
  ollamaList: (endpoint) => ipcRenderer.invoke("ollama:list", endpoint),
  ollamaRecommended: (vramGB) => ipcRenderer.invoke("ollama:recommended", vramGB),
  ollamaPull: (model) => ipcRenderer.invoke("ollama:pull", model),
  onOllamaProgress: (cb) => ipcRenderer.on("ollama-progress", (_e, payload) => cb(payload)),
  openWizard: () => ipcRenderer.invoke("wizard:open"),
  openExternal: (url) => ipcRenderer.invoke("external:open", url),
  closeWizard: () => ipcRenderer.invoke("wizard-window:close"),
  wizardCatalog: () => ipcRenderer.invoke("wizard:catalog"),
  downloadsEnqueue: (spec) => ipcRenderer.invoke("downloads:enqueue", spec),
  downloadsList: () => ipcRenderer.invoke("downloads:list"),
  downloadsCancel: (id) => ipcRenderer.invoke("downloads:cancel", id),
  downloadsClearFinished: () => ipcRenderer.invoke("downloads:clear-finished"),
  onDownloadsChanged: (cb) => ipcRenderer.on("downloads-changed", (_e, payload) => cb(payload)),
  bookList: () => ipcRenderer.invoke("book:list"),
  bookCreate: (title) => ipcRenderer.invoke("book:create", title),
  bookGet: (id) => ipcRenderer.invoke("book:get", id),
  bookSetStage: (id, stage) => ipcRenderer.invoke("book:set-stage", { id, stage }),
  bookAddChapter: (id, title) => ipcRenderer.invoke("book:add-chapter", { id, title }),
  bookSetChapterStatus: (id, chapterId, status) => ipcRenderer.invoke("book:set-chapter-status", { id, chapterId, status }),
  bookAddRecord: (id, type, name, content) => ipcRenderer.invoke("book:add-record", { id, type, name, content }),
  bookReadRecord: (id, recordId) => ipcRenderer.invoke("book:read-record", { id, recordId }),
  bookSetRecord: (id, recordId, content) => ipcRenderer.invoke("book:set-record", { id, recordId, content }),
  bookLog: (id, text) => ipcRenderer.invoke("book:log", { id, text }),
  bookOpenFolder: (id) => ipcRenderer.invoke("book:open-folder", id),
  bookTask: (id, taskId, chapterId) => ipcRenderer.invoke("book:task", { id, taskId, chapterId }),
  bookBrief: (id) => ipcRenderer.invoke("book:brief", id),
  bookWorkflowStart: (id, chapterId) => ipcRenderer.invoke("book:workflow-start", { id, chapterId }),
  bookWorkflowNext: (id, chapterId) => ipcRenderer.invoke("book:workflow-next", { id, chapterId }),
  bookWorkflowSetStatus: (id, status) => ipcRenderer.invoke("book:workflow-set-status", { id, status }),
  bookSendRules: (id) => ipcRenderer.invoke("book:send-rules", { id }),
  bookPdfGate: (id) => ipcRenderer.invoke("book:pdf-gate", id),
  bookGeneratePdfs: (id) => ipcRenderer.invoke("book:generate-pdfs", id),
  bookScanPdfs: (id) => ipcRenderer.invoke("book:scan-pdfs", id),
  bookOpenPdf: (id, file) => ipcRenderer.invoke("book:open-pdf", { id, file }),
  bookOpenPdfsFolder: (id) => ipcRenderer.invoke("book:open-pdfs-folder", id),
  bookAssemble: (id) => ipcRenderer.invoke("book:assemble", id),
  bookGovernedAvailable: () => ipcRenderer.invoke("book:governed-available"),
  bookAiStatus: () => ipcRenderer.invoke("book:ai-status"),
  bookTestRun: () => ipcRenderer.invoke("book:test-run"),
  bookRunnerStatus: () => ipcRenderer.invoke("book:runner-status"),
  bookRecordStart: (id) => ipcRenderer.invoke("book:record-start", id),
  bookRecordStop: () => ipcRenderer.invoke("book:record-stop"),
  bookRecordStatus: () => ipcRenderer.invoke("book:record-status"),
  onBookRecording: (cb) => ipcRenderer.on("book-recording", (_e, payload) => cb(payload)),
  onBookRunner: (cb) => ipcRenderer.on("book-runner", (_e, payload) => cb(payload)),
  // ATELIER v3 engine cockpit
  atelierStart: (id) => ipcRenderer.invoke("atelier-engine:start", id),
  atelierRequirements: (id, body, mandatory) => ipcRenderer.invoke("atelier-engine:requirements", { id, body, mandatory }),
  atelierAdvance: (id) => ipcRenderer.invoke("atelier-engine:advance", id),
  atelierStatus: (id) => ipcRenderer.invoke("atelier-engine:status", id),
  onAtelierStatus: (cb) => ipcRenderer.on("atelier-status", (_e, payload) => cb(payload)),
  onAtelierNote: (cb) => ipcRenderer.on("atelier-note", (_e, payload) => cb(payload))
});
