// preload.js — runs in the control panel pane before controls.html loads. Exposes a
// small, explicit API bridge instead of giving the renderer raw Node/IPC access.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  sendCompose: (text, targets) => ipcRenderer.invoke("send:compose", { text, targets }),
  sendForward: (source, targets) => ipcRenderer.invoke("send:forward", { source, targets }),
  regenerate: (site) => ipcRenderer.invoke("send:regenerate", site),
  setRouting: (source, target, enabled) => ipcRenderer.invoke("routing:set", { source, target, enabled }),
  pauseAllRouting: () => ipcRenderer.invoke("routing:pause-all"),
  stopAllRouting: () => ipcRenderer.invoke("routing:stop-all"),
  autoAllRouting: () => ipcRenderer.invoke("routing:auto-all"),
  setParticipant: (site, enabled) => ipcRenderer.invoke("participants:set", { site, enabled }),
  startHouseRule: (mode, topic, rounds) => ipcRenderer.invoke("houserule:start", { mode, topic, rounds }),
  stopHouseRule: () => ipcRenderer.invoke("houserule:stop"),
  pauseHouseRule: () => ipcRenderer.invoke("houserule:pause"),
  resumeHouseRule: () => ipcRenderer.invoke("houserule:resume"),
  wrapUpBrainstorm: () => ipcRenderer.invoke("houserule:wrap-up-brainstorm"),
  setRole: (site, role) => ipcRenderer.invoke("roles:set", { site, role }),
  savePrompt: (id, name, text) => ipcRenderer.invoke("prompts:save", { id, name, text }),
  deletePrompt: (id) => ipcRenderer.invoke("prompts:delete", id),
  sendPrompt: (text) => ipcRenderer.invoke("prompts:send", { text }),
  openPromptEditor: (id) => ipcRenderer.invoke("prompts:open-editor", id),
  closePromptEditor: () => ipcRenderer.invoke("prompt-editor:close"),
  onPromptsChanged: (cb) => ipcRenderer.on("prompts-changed", (_e, payload) => cb(payload)),
  getState: () => ipcRenderer.invoke("state:get"),
  clearTranscript: () => ipcRenderer.invoke("transcript:clear"),
  extractAllLogs: () => ipcRenderer.invoke("logs:extract-all"),
  togglePin: (id) => ipcRenderer.invoke("transcript:toggle-pin", id),
  reloadSite: (site) => ipcRenderer.invoke("site:reload", site),
  startNewChatAll: () => ipcRenderer.invoke("sites:new-chat-all"),
  inspectSite: (site) => ipcRenderer.invoke("site:inspect", site),
  listSites: () => ipcRenderer.invoke("site:list"),
  setZoom: (site, factor) => ipcRenderer.invoke("site:zoom", { site, factor }),
  pickSelector: (site, role) => ipcRenderer.invoke("selector:pick", { site, role }),
  clearSelectorOverride: (site, role) => ipcRenderer.invoke("selector:clear", { site, role }),
  runSelfTest: (site) => ipcRenderer.invoke("selftest:run", { site }),
  runTuner: () => ipcRenderer.invoke("tuner:run"),
  onTunerState: (cb) => ipcRenderer.on("tuner-state", (_e, payload) => cb(payload)),
  listSavedLogins: () => ipcRenderer.invoke("logins:list"),
  saveLogin: (site, label, username, password) => ipcRenderer.invoke("logins:save", { site, label, username, password }),
  deleteLogin: (site, id) => ipcRenderer.invoke("logins:delete", { site, id }),
  fillLogin: (site, id) => ipcRenderer.invoke("logins:fill", { site, id }),
  openSequenceEditor: () => ipcRenderer.invoke("sequence:open"),
  closeSequenceEditor: () => ipcRenderer.invoke("sequence-editor:close"),
  runSequence: (steps) => ipcRenderer.invoke("sequence:run", { steps }),
  stopSequence: () => ipcRenderer.invoke("sequence:stop"),
  onSequenceState: (cb) => ipcRenderer.on("sequence-state", (_e, payload) => cb(payload)),
  toggleWindowCollapse: (which) => ipcRenderer.invoke("window:toggle-collapse", { which }),
  openFeed: () => ipcRenderer.invoke("feed:open"),
  closeFeed: () => ipcRenderer.invoke("feed-window:close"),
  feedHistory: () => ipcRenderer.invoke("feed:history"),
  onCapture: (cb) => ipcRenderer.on("capture", (_e, payload) => cb(payload)),
  onWindowCollapseChanged: (cb) => ipcRenderer.on("window-collapse-changed", (_e, payload) => cb(payload)),
  onSent: (cb) => ipcRenderer.on("sent", (_e, payload) => cb(payload)),
  onSendError: (cb) => ipcRenderer.on("send-error", (_e, payload) => cb(payload)),
  onWaitingChanged: (cb) => ipcRenderer.on("waiting-changed", (_e, payload) => cb(payload)),
  onHouseRuleState: (cb) => ipcRenderer.on("houserule-state", (_e, payload) => cb(payload)),
  onLog: (cb) => ipcRenderer.on("log", (_e, payload) => cb(payload)),
  uiLog: (action, detail) => ipcRenderer.invoke("ui:log", Object.assign({ action }, detail || {})),
  onLedgerEntry: (cb) => ipcRenderer.on("ledger-entry", (_e, payload) => cb(payload)),
  startManagedTask: (userRequest) => ipcRenderer.invoke("manager:start-task", { userRequest }),
  pauseManagedTask: () => ipcRenderer.invoke("manager:pause"),
  resumeManagedTask: () => ipcRenderer.invoke("manager:resume"),
  stopManagedTask: () => ipcRenderer.invoke("manager:stop"),
  approveManagerAction: () => ipcRenderer.invoke("manager:approve"),
  rejectManagerAction: (reason) => ipcRenderer.invoke("manager:reject", { reason }),
  configureManagerProvider: (config) => ipcRenderer.invoke("manager:configure-provider", config),
  testManagerConnection: () => ipcRenderer.invoke("manager:test-connection"),
  getManagerState: () => ipcRenderer.invoke("manager:get-state"),
  onManagerState: (cb) => ipcRenderer.on("manager-state", (_e, payload) => cb(payload)),
  onManagerLog: (cb) => ipcRenderer.on("manager-log", (_e, payload) => cb(payload)),
  onManagerAck: (cb) => ipcRenderer.on("manager-ack", (_e, payload) => cb(payload)),
  // N5 Tools
  toolsList: () => ipcRenderer.invoke("tools:list"),
  toolsRun: (tool, args) => ipcRenderer.invoke("tools:run", { tool, args }),
  // N3 Memory
  memorySummary: () => ipcRenderer.invoke("memory:summary"),
  memorySearch: (query) => ipcRenderer.invoke("memory:search", { query }),
  // N2 Voice
  voiceStatus: () => ipcRenderer.invoke("voice:status"),
  configureVoice: (patch) => ipcRenderer.invoke("voice:configure", patch),
  voiceSpeak: (text) => ipcRenderer.invoke("voice:speak", { text }),
  voiceListen: (opts) => ipcRenderer.invoke("voice:listen", opts || {}),
  // Image generation (Stable Diffusion)
  imageStatus: () => ipcRenderer.invoke("image:status"),
  configureImage: (patch) => ipcRenderer.invoke("image:configure", patch),
  imageGenerate: (prompt, negativePrompt) => ipcRenderer.invoke("image:generate", { prompt, negativePrompt }),
  dbStatus: () => ipcRenderer.invoke("db:status"),
  dbRecentMessages: (limit) => ipcRenderer.invoke("db:recent-messages", limit),
  ollamaDetect: () => ipcRenderer.invoke("ollama:detect"),
  ollamaList: (endpoint) => ipcRenderer.invoke("ollama:list", endpoint),
  ollamaRecommended: (vramGB) => ipcRenderer.invoke("ollama:recommended", vramGB),
  ollamaPull: (model) => ipcRenderer.invoke("ollama:pull", model),
  onOllamaProgress: (cb) => ipcRenderer.on("ollama-progress", (_e, payload) => cb(payload)),
  openWizard: (tab) => ipcRenderer.invoke("wizard:open", { tab }),
  openExternal: (url) => ipcRenderer.invoke("external:open", url),
  closeWizard: () => ipcRenderer.invoke("wizard-window:close"),
  wizardCatalog: () => ipcRenderer.invoke("wizard:catalog")
});
